// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkdmueujbxyeiqunpiso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZG11ZXVqYnh5ZWlxdW5waXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMzAwMjAsImV4cCI6MjA4NTYwNjAyMH0.yqe7BGwZCUJQvRqFs2xjPy8b-Qi_5Bh0WDkUDZsfwHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});